env:
  browser: true
  es6: true
  node: true
extends:
  - 'airbnb'
  - 'eslint:recommended'
  - 'plugin:react/recommended'
globals:
  Atomics: readonly
  SharedArrayBuffer: readonly
parser: "babel-eslint"
parserOptions:
  ecmaFeatures:
    jsx: true
    experimentalObjectRestSpread: true
  ecmaVersion: 2018
  sourceType: module
plugins:
  - react
rules: {
  semi: ["error", "never"],
  arrow-parens: ["error", "as-needed"],
  space-before-function-paren: ["error", "always"],
  import/no-unresolved: 0,
  no-shadow: 0,
  react/jsx-filename-extension: [1, { "extensions": [".js", ".jsx"] }],
  react/state-in-constructor: 0,
  react/button-has-type: 0,
  func-names: 0,
  import/extensions: 0,
  quote-props: 0,
  react/prop-types: 0,
  jsx-a11y/control-has-associated-label: 0,
  no-unused-expressions: 0,
  import/no-named-as-default: 0,
  object-curly-newline: 0,
  jsx-a11y/no-static-element-interactions: 0,
  jsx-a11y/click-events-have-key-events: 0,
  react/jsx-props-no-spreading: 0,
  no-prototype-builtins: 0,
  react/jsx-one-expression-per-line: 0,
  import/prefer-default-export: 0,
  react/destructuring-assignment: 0,
  no-underscore-dangle: 0,
  jsx-a11y/no-noninteractive-element-interactions: 0,
  react/no-array-index-key: 0,
  react/display-name: 0,
  no-mixed-operators: 0,
  consistent-return: 0,
}
