env:
  browser: true
  es6: true
  node: true
extends:
  - 'airbnb'
  - 'eslint:recommended'
  # - 'plugin:react/recommended'
globals:
  Atomics: readonly
  SharedArrayBuffer: readonly
parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: 2018
  sourceType: module
plugins:
  - react
rules: {
  semi: ["error", "never"],
  arrow-parens: ["error", "as-needed"],
  space-before-function-paren: ["error", "always"],
  import/no-unresolved: 0,
  no-shadow: 0,
}
