module.exports = {
  common: {
    VERIFY_OWNER: 'VERIFY_OWNER',
  },
  devise: {
    DEVISE_STATUS: 'DEVISE_STATUS',
    DEVISE_UPDATE: 'DEVISE_UPDATE',
    DEVISE_CONNECTION: 'DEVISE_CONNECTION',
  },
  user: {
    UPDATE_DEVISE: 'DEVISES:UPDATE_ONE',
    USER_CONNECTION: 'USER_CONNECTION',
  },
}
